name: hello-world
on: [push]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: Say hello
        run: echo "$(cat hello_world.txt)"
